[build]
  Command = "yarn build && yarn build:lambda"
  Functions = "lambda"
  Publish = "build"

[template.environment]
  API_KEY = "Your secret Airtable API key"
  REACT_APP_AIRTABLE_BASE_ID = "Your Airtable Base ID"